#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 16 21:11:11 2024

@author: rajpatel
"""

def MakeModelArch(lyrs, nodes, hidden_act, out_act, num_params):
    model_temp = Sequential()
    model_temp.add(Dense(nodes, input_shape=(num_params,), activation=hidden_act))
    for i in range(lyrs-1):
        model_temp.add(Dense(nodes, activation=hidden_act))
    model_temp.add(Dense(1, activation=out_act))
    return model_temp